CLS

echo Installing npm packages...
echo Installing @wrappid/styles...
echo Installing @wrappid/sc-mobile with alias styled-components...
echo Installing @wrappid/core...
call npm i %WRAPPID_HOME%\styles\dist @wrappid/styled-components@file:%WRAPPID_HOME%\sc-mobile\dist %WRAPPID_HOME%\core\dist